version: "3.7"
services:
  app:
    build:
      args:
        user: app_user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    tty: true
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - "./:/var/www:delegated"